/*  
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 
Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.

=== Algo design ===
s = "abcd", t = "abcde"

"st"
"t"

map = {
    a: "s"
}

sMap = {
    a: 1
    b: 1
    c: 1
    d: 1
}

tMap = {
    a: 1
    b: 1
    c: 1
    d: 1
    e => this doesn't existing in sMap
}

- return the tMap[key] that doesn't exist in sMap 

=== Pseudocode ===
tMap = {}

loop over t
    sChar = s[i]
    tChar = t[i]

    if (tMap[tChar] !== sChar){
        return tChar
    }

    add elements to the maps 
    tMap[tChar] = sChar

=== Big O analysis === 
*/

var findTheDifference = function (s, t) {
  let sMap = {};
  let tMap = {};

  for (let char of s) {
    if (!sMap[char]) {
      sMap[char] = 1;
    } else {
      sMap[char] += 1;
    }
  }

  for (let char of t) {
    if (!tMap[char]) {
      tMap[char] = 1;
    } else {
      tMap[char] += 1;
    }
  }

  for (let [key, value] of Object.entries(tMap)) {
    if (!sMap[key] || value !== sMap[key]) {
      return key;
    }
  }
};

findTheDifference("a", "aa");
